# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-24 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=200, verbose_name='歌曲')),
                ('singer_name', models.CharField(max_length=200, verbose_name='歌手')),
                ('play_url', models.CharField(max_length=500, verbose_name='播放链接')),
                ('wyy_music_id', models.IntegerField(default=0, verbose_name='某云歌曲id')),
            ],
        ),
    ]
