# Generated by Django 2.2.12 on 2020-06-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200612_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=50, verbose_name='作者'),
        ),
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
