# Generated by Django 2.2.12 on 2020-06-15 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_auto_20200613_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作家', 'verbose_name_plural': '作家'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书', 'verbose_name_plural': '图书'},
        ),
    ]
