# Generated by Django 2.2.12 on 2020-06-15 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otd', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
        migrations.AlterModelTable(
            name='publisher',
            table=None,
        ),
    ]
