# Generated by Django 2.2.12 on 2020-06-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '丈夫', 'verbose_name_plural': '丈夫'},
        ),
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': '妻子', 'verbose_name_plural': '妻子'},
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='姓名'),
        ),
    ]
