# Generated by Django 2.2.12 on 2020-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0002_auto_20200615_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='作家'),
        ),
    ]
