# Generated by Django 2.2.12 on 2020-06-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oto', '0003_auto_20200615_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oto.Author', verbose_name='作家'),
        ),
    ]
