# Generated by Django 2.2.12 on 2020-06-30 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
